# Usar as configurações padrões do SearXNG para todos os motores (Web, Imagens, News, etc.)
use_default_settings: true

general:
  instance_name: "Atlas Forge SearXNG"
  debug: false
  contact_url: false
  donation_url: false
  enable_metrics: false

server:
  secret_key: "atlas-forge-searxng-k9x2m4p7q1w5e8r3t6y0u2i4o7a5s1d3f"
  bind_address: "0.0.0.0"
  port: 8080
  limiter: false
  image_proxy: true # Ativar o proxy de imagem ajuda a carregar imagens que bloqueiam hotlinking

search:
  formats:
    - html
    - json
  safe_search: 0
  autocomplete: ""
  default_lang: "pt-BR"
  max_page: 50
  results_on_each_page: 50

ui:
  static_use_hash: true
  default_locale: "pt"
  default_theme: "simple"

outgoing:
  request_timeout: 5.0
  max_request_timeout: 15.0
