import { DesignSystem } from "./types";

export const DESIGN_SYSTEMS: DesignSystem[] = [
  // ═══════════════════════════════════════════════════════════════
  // TECH (10)
  // ═══════════════════════════════════════════════════════════════
  {
    id: "stripe",
    name: "Stripe",
    category: "tech",
    colors: {
      primary: "#635BFF",
      secondary: "#0A2540",
      accent: "#00D4AA",
      background: "#0A2540",
      surface: "#1A3550",
      text: "#FFFFFF",
      muted: "#8898AA",
    },
    fonts: { display: "system-ui", body: "system-ui", mono: "monospace" },
    borderRadius: "12px",
    shadows: "0 4px 24px rgba(99,91,255,0.25)",
    borders: "1px solid rgba(255,255,255,0.08)",
  },
  {
    id: "linear",
    name: "Linear",
    category: "tech",
    colors: {
      primary: "#5E6AD2",
      secondary: "#171923",
      accent: "#F2C94C",
      background: "#0E0F15",
      surface: "#1A1B26",
      text: "#FFFFFF",
      muted: "#6B7280",
    },
    fonts: { display: "system-ui", body: "system-ui", mono: "monospace" },
    borderRadius: "8px",
    shadows: "0 2px 12px rgba(0,0,0,0.4)",
    borders: "1px solid rgba(255,255,255,0.06)",
  },
  {
    id: "vercel",
    name: "Vercel",
    category: "tech",
    colors: {
      primary: "#000000",
      secondary: "#71717A",
      accent: "#0070F3",
      background: "#000000",
      surface: "#111111",
      text: "#FFFFFF",
      muted: "#A1A1AA",
    },
    fonts: { display: "system-ui", body: "system-ui", mono: "monospace" },
    borderRadius: "0px",
    shadows: "none",
    borders: "1px solid #333333",
  },
  {
    id: "notion",
    name: "Notion",
    category: "tech",
    colors: {
      primary: "#000000",
      secondary: "#37352F",
      accent: "#2EAADC",
      background: "#FFFFFF",
      surface: "#F7F6F3",
      text: "#37352F",
      muted: "#9B9A97",
    },
    fonts: { display: "system-ui", body: "system-ui", mono: "monospace" },
    borderRadius: "4px",
    shadows: "none",
    borders: "none",
  },
  {
    id: "figma",
    name: "Figma",
    category: "tech",
    colors: {
      primary: "#0ACF83",
      secondary: "#1E1E1E",
      accent: "#F24E1E",
      background: "#2C2C2C",
      surface: "#383838",
      text: "#FFFFFF",
      muted: "#B3B3B3",
    },
    fonts: { display: "system-ui", body: "system-ui", mono: "monospace" },
    borderRadius: "8px",
    shadows: "0 2px 8px rgba(0,0,0,0.3)",
    borders: "none",
  },
  {
    id: "raycast",
    name: "Raycast",
    category: "tech",
    colors: {
      primary: "#FF6363",
      secondary: "#1D1D1D",
      accent: "#FFD60A",
      background: "#141414",
      surface: "#1E1E1E",
      text: "#FFFFFF",
      muted: "#6E6E6E",
    },
    fonts: { display: "system-ui", body: "system-ui", mono: "monospace" },
    borderRadius: "12px",
    shadows: "0 4px 20px rgba(255,99,99,0.15)",
    borders: "1px solid rgba(255,255,255,0.05)",
  },
  {
    id: "arc",
    name: "Arc Browser",
    category: "tech",
    colors: {
      primary: "#FF6B6B",
      secondary: "#1A1A2E",
      accent: "#4ECDC4",
      background: "#0F0F1A",
      surface: "#1A1A2E",
      text: "#FFFFFF",
      muted: "#7B7B8E",
    },
    fonts: { display: "system-ui", body: "system-ui", mono: "monospace" },
    borderRadius: "16px",
    shadows: "0 8px 32px rgba(78,205,196,0.15)",
    borders: "1px solid rgba(255,255,255,0.06)",
  },
  {
    id: "claude",
    name: "Claude",
    category: "tech",
    colors: {
      primary: "#CC785C",
      secondary: "#D4A574",
      accent: "#CC785C",
      background: "#F5EDE3",
      surface: "#FFFFFF",
      text: "#2D2016",
      muted: "#9A8C7E",
    },
    fonts: { display: "Georgia", body: "system-ui", mono: "monospace" },
    borderRadius: "12px",
    shadows: "0 2px 12px rgba(0,0,0,0.08)",
    borders: "1px solid rgba(0,0,0,0.06)",
  },
  {
    id: "supabase",
    name: "Supabase",
    category: "tech",
    colors: {
      primary: "#3ECF8E",
      secondary: "#1C1C1C",
      accent: "#3ECF8E",
      background: "#0A0A0A",
      surface: "#181818",
      text: "#FFFFFF",
      muted: "#888888",
    },
    fonts: { display: "system-ui", body: "system-ui", mono: "monospace" },
    borderRadius: "8px",
    shadows: "0 0 24px rgba(62,207,142,0.15)",
    borders: "1px solid rgba(62,207,142,0.2)",
  },
  {
    id: "resend",
    name: "Resend",
    category: "tech",
    colors: {
      primary: "#000000",
      secondary: "#525252",
      accent: "#000000",
      background: "#FFFFFF",
      surface: "#F5F5F5",
      text: "#000000",
      muted: "#A3A3A3",
    },
    fonts: { display: "system-ui", body: "system-ui", mono: "monospace" },
    borderRadius: "8px",
    shadows: "none",
    borders: "1px solid #E5E5E5",
  },

  // ═══════════════════════════════════════════════════════════════
  // MINIMAL (8)
  // ═══════════════════════════════════════════════════════════════
  {
    id: "apple",
    name: "Apple",
    category: "minimal",
    colors: {
      primary: "#000000",
      secondary: "#86868B",
      accent: "#0071E3",
      background: "#FFFFFF",
      surface: "#F5F5F7",
      text: "#1D1D1F",
      muted: "#86868B",
    },
    fonts: { display: "system-ui", body: "system-ui", mono: "monospace" },
    borderRadius: "0px",
    shadows: "none",
    borders: "none",
  },
  {
    id: "muji",
    name: "Muji",
    category: "minimal",
    colors: {
      primary: "#3D3229",
      secondary: "#6B5E4F",
      accent: "#C4A882",
      background: "#F5F0E8",
      surface: "#FFFFFF",
      text: "#3D3229",
      muted: "#9B8E7E",
    },
    fonts: { display: "Georgia", body: "system-ui", mono: "monospace" },
    borderRadius: "0px",
    shadows: "none",
    borders: "1px solid #E0D8CC",
  },
  {
    id: "aesop",
    name: "Aesop",
    category: "minimal",
    colors: {
      primary: "#3D3229",
      secondary: "#8B7355",
      accent: "#C4956A",
      background: "#F5EDE3",
      surface: "#FFFFFF",
      text: "#3D3229",
      muted: "#9B8E7E",
    },
    fonts: { display: "Georgia", body: "Georgia", mono: "monospace" },
    borderRadius: "0px",
    shadows: "none",
    borders: "1px solid rgba(0,0,0,0.06)",
  },
  {
    id: "dieter-rams",
    name: "Dieter Rams",
    category: "minimal",
    colors: {
      primary: "#1A1A1A",
      secondary: "#666666",
      accent: "#E8E8E8",
      background: "#FFFFFF",
      surface: "#F0F0F0",
      text: "#1A1A1A",
      muted: "#999999",
    },
    fonts: { display: "system-ui", body: "system-ui", mono: "monospace" },
    borderRadius: "0px",
    shadows: "none",
    borders: "1px solid #E0E0E0",
  },
  {
    id: "kinfolk",
    name: "Kinfolk",
    category: "minimal",
    colors: {
      primary: "#1A1A1A",
      secondary: "#888888",
      accent: "#1A1A1A",
      background: "#FFFFFF",
      surface: "#FAFAFA",
      text: "#1A1A1A",
      muted: "#AAAAAA",
    },
    fonts: { display: "Georgia", body: "Georgia", mono: "monospace" },
    borderRadius: "0px",
    shadows: "none",
    borders: "none",
  },
  {
    id: "cereal",
    name: "Cereal (Airbnb)",
    category: "minimal",
    colors: {
      primary: "#FF5A5F",
      secondary: "#484848",
      accent: "#FF5A5F",
      background: "#FFFFFF",
      surface: "#F7F7F7",
      text: "#484848",
      muted: "#767676",
    },
    fonts: { display: "system-ui", body: "system-ui", mono: "monospace" },
    borderRadius: "8px",
    shadows: "none",
    borders: "1px solid #EBEBEB",
  },
  {
    id: "helvetica",
    name: "Helvetica",
    category: "minimal",
    colors: {
      primary: "#000000",
      secondary: "#555555",
      accent: "#E50000",
      background: "#FFFFFF",
      surface: "#F2F2F2",
      text: "#000000",
      muted: "#999999",
    },
    fonts: { display: "system-ui", body: "system-ui", mono: "monospace" },
    borderRadius: "0px",
    shadows: "none",
    borders: "1px solid #DDDDDD",
  },
  {
    id: "dieter-rams-light",
    name: "Dieter Rams Light",
    category: "minimal",
    colors: {
      primary: "#333333",
      secondary: "#888888",
      accent: "#FF6B35",
      background: "#FAFAFA",
      surface: "#FFFFFF",
      text: "#333333",
      muted: "#AAAAAA",
    },
    fonts: { display: "system-ui", body: "system-ui", mono: "monospace" },
    borderRadius: "4px",
    shadows: "0 1px 3px rgba(0,0,0,0.05)",
    borders: "1px solid #EEEEEE",
  },

  // ═══════════════════════════════════════════════════════════════
  // BOLD (8)
  // ═══════════════════════════════════════════════════════════════
  {
    id: "tesla",
    name: "Tesla",
    category: "bold",
    colors: {
      primary: "#CC0000",
      secondary: "#000000",
      accent: "#CC0000",
      background: "#000000",
      surface: "#111111",
      text: "#FFFFFF",
      muted: "#888888",
    },
    fonts: { display: "system-ui", body: "system-ui", mono: "monospace" },
    borderRadius: "0px",
    shadows: "none",
    borders: "none",
  },
  {
    id: "nike",
    name: "Nike",
    category: "bold",
    colors: {
      primary: "#111111",
      secondary: "#FFFFFF",
      accent: "#FF6B35",
      background: "#111111",
      surface: "#1A1A1A",
      text: "#FFFFFF",
      muted: "#888888",
    },
    fonts: { display: "system-ui", body: "system-ui", mono: "monospace" },
    borderRadius: "0px",
    shadows: "none",
    borders: "none",
  },
  {
    id: "spotify",
    name: "Spotify",
    category: "bold",
    colors: {
      primary: "#1DB954",
      secondary: "#191414",
      accent: "#1DB954",
      background: "#121212",
      surface: "#181818",
      text: "#FFFFFF",
      muted: "#B3B3B3",
    },
    fonts: { display: "system-ui", body: "system-ui", mono: "monospace" },
    borderRadius: "8px",
    shadows: "0 4px 20px rgba(29,185,84,0.2)",
    borders: "none",
  },
  {
    id: "supreme",
    name: "Supreme",
    category: "bold",
    colors: {
      primary: "#E31937",
      secondary: "#FFFFFF",
      accent: "#E31937",
      background: "#FFFFFF",
      surface: "#F5F5F5",
      text: "#000000",
      muted: "#666666",
    },
    fonts: { display: "system-ui", body: "system-ui", mono: "monospace" },
    borderRadius: "0px",
    shadows: "none",
    borders: "none",
  },
  {
    id: "balenciaga",
    name: "Balenciaga",
    category: "bold",
    colors: {
      primary: "#000000",
      secondary: "#666666",
      accent: "#000000",
      background: "#FFFFFF",
      surface: "#F0F0F0",
      text: "#000000",
      muted: "#999999",
    },
    fonts: { display: "system-ui", body: "system-ui", mono: "monospace" },
    borderRadius: "0px",
    shadows: "none",
    borders: "none",
  },
  {
    id: "off-white",
    name: "Off-White",
    category: "bold",
    colors: {
      primary: "#000000",
      secondary: "#FFC83D",
      accent: "#FFC83D",
      background: "#FFFFFF",
      surface: "#F5F5F5",
      text: "#000000",
      muted: "#888888",
    },
    fonts: { display: "system-ui", body: "system-ui", mono: "monospace" },
    borderRadius: "0px",
    shadows: "none",
    borders: "2px solid #000000",
  },
  {
    id: "supreme-dark",
    name: "Supreme Dark",
    category: "bold",
    colors: {
      primary: "#E31937",
      secondary: "#FFFFFF",
      accent: "#E31937",
      background: "#111111",
      surface: "#1A1A1A",
      text: "#FFFFFF",
      muted: "#888888",
    },
    fonts: { display: "system-ui", body: "system-ui", mono: "monospace" },
    borderRadius: "0px",
    shadows: "none",
    borders: "none",
  },
  {
    id: "nike-sport",
    name: "Nike Sport",
    category: "bold",
    colors: {
      primary: "#FA5400",
      secondary: "#111111",
      accent: "#FA5400",
      background: "#111111",
      surface: "#1C1C1C",
      text: "#FFFFFF",
      muted: "#888888",
    },
    fonts: { display: "system-ui", body: "system-ui", mono: "monospace" },
    borderRadius: "4px",
    shadows: "0 4px 16px rgba(250,84,0,0.2)",
    borders: "none",
  },

  // ═══════════════════════════════════════════════════════════════
  // CORPORATIVO (8)
  // ═══════════════════════════════════════════════════════════════
  {
    id: "mckinsey",
    name: "McKinsey",
    category: "corporativo",
    colors: {
      primary: "#051C2C",
      secondary: "#0067B1",
      accent: "#0067B1",
      background: "#FFFFFF",
      surface: "#F2F6FA",
      text: "#051C2C",
      muted: "#6E8494",
    },
    fonts: { display: "Georgia", body: "system-ui", mono: "monospace" },
    borderRadius: "0px",
    shadows: "none",
    borders: "1px solid #D6E4EE",
  },
  {
    id: "bcg",
    name: "BCG",
    category: "corporativo",
    colors: {
      primary: "#00875A",
      secondary: "#051C2C",
      accent: "#00875A",
      background: "#FFFFFF",
      surface: "#F0F7F4",
      text: "#051C2C",
      muted: "#6E8494",
    },
    fonts: { display: "Georgia", body: "system-ui", mono: "monospace" },
    borderRadius: "0px",
    shadows: "none",
    borders: "1px solid #C8E6D8",
  },
  {
    id: "bain",
    name: "Bain",
    category: "corporativo",
    colors: {
      primary: "#CC0000",
      secondary: "#051C2C",
      accent: "#CC0000",
      background: "#FFFFFF",
      surface: "#FDF2F2",
      text: "#051C2C",
      muted: "#8C6D70",
    },
    fonts: { display: "Georgia", body: "system-ui", mono: "monospace" },
    borderRadius: "0px",
    shadows: "none",
    borders: "1px solid #F0D0D0",
  },
  {
    id: "deloitte",
    name: "Deloitte",
    category: "corporativo",
    colors: {
      primary: "#86BC25",
      secondary: "#051C2C",
      accent: "#86BC25",
      background: "#FFFFFF",
      surface: "#F5F8F0",
      text: "#051C2C",
      muted: "#6E8494",
    },
    fonts: { display: "system-ui", body: "system-ui", mono: "monospace" },
    borderRadius: "0px",
    shadows: "none",
    borders: "1px solid #D6E8C8",
  },
  {
    id: "accenture",
    name: "Accenture",
    category: "corporativo",
    colors: {
      primary: "#A100FF",
      secondary: "#051C2C",
      accent: "#A100FF",
      background: "#FFFFFF",
      surface: "#F5F0FA",
      text: "#051C2C",
      muted: "#7B6B8A",
    },
    fonts: { display: "system-ui", body: "system-ui", mono: "monospace" },
    borderRadius: "0px",
    shadows: "none",
    borders: "1px solid #E0D0F0",
  },
  {
    id: "forbes",
    name: "Forbes",
    category: "corporativo",
    colors: {
      primary: "#000000",
      secondary: "#CC0000",
      accent: "#CC0000",
      background: "#FFFFFF",
      surface: "#F5F5F5",
      text: "#000000",
      muted: "#888888",
    },
    fonts: { display: "Georgia", body: "Georgia", mono: "monospace" },
    borderRadius: "0px",
    shadows: "none",
    borders: "1px solid #E0E0E0",
  },
  {
    id: "hbr",
    name: "Harvard Business Review",
    category: "corporativo",
    colors: {
      primary: "#CC0000",
      secondary: "#051C2C",
      accent: "#CC0000",
      background: "#FFFFFF",
      surface: "#FDF5F5",
      text: "#051C2C",
      muted: "#8C6D70",
    },
    fonts: { display: "Georgia", body: "Georgia", mono: "monospace" },
    borderRadius: "0px",
    shadows: "none",
    borders: "1px solid #F0D0D0",
  },
  {
    id: "bloomberg-terminal",
    name: "Bloomberg",
    category: "corporativo",
    colors: {
      primary: "#FF6600",
      secondary: "#000000",
      accent: "#FF6600",
      background: "#000000",
      surface: "#111111",
      text: "#FF6600",
      muted: "#888800",
    },
    fonts: { display: "monospace", body: "monospace", mono: "monospace" },
    borderRadius: "0px",
    shadows: "none",
    borders: "1px solid #333300",
  },

  // ═══════════════════════════════════════════════════════════════
  // EDITORIAL (8)
  // ═══════════════════════════════════════════════════════════════
  {
    id: "nyt",
    name: "NYT",
    category: "editorial",
    colors: {
      primary: "#000000",
      secondary: "#567B95",
      accent: "#567B95",
      background: "#FFFFFF",
      surface: "#F7F7F7",
      text: "#121212",
      muted: "#666666",
    },
    fonts: { display: "Georgia", body: "Georgia", mono: "monospace" },
    borderRadius: "0px",
    shadows: "none",
    borders: "none",
  },
  {
    id: "economist",
    name: "The Economist",
    category: "editorial",
    colors: {
      primary: "#E3120B",
      secondary: "#1A1A1A",
      accent: "#E3120B",
      background: "#FFFFFF",
      surface: "#F5F5F5",
      text: "#1A1A1A",
      muted: "#888888",
    },
    fonts: { display: "Georgia", body: "Georgia", mono: "monospace" },
    borderRadius: "0px",
    shadows: "none",
    borders: "1px solid #E0E0E0",
  },
  {
    id: "bloomberg-editorial",
    name: "Bloomberg Editorial",
    category: "editorial",
    colors: {
      primary: "#000000",
      secondary: "#4A4A4A",
      accent: "#FF6600",
      background: "#FFFFFF",
      surface: "#F5F5F5",
      text: "#1A1A1A",
      muted: "#888888",
    },
    fonts: { display: "Georgia", body: "Georgia", mono: "monospace" },
    borderRadius: "0px",
    shadows: "none",
    borders: "1px solid #E0E0E0",
  },
  {
    id: "monocle",
    name: "Monocle",
    category: "editorial",
    colors: {
      primary: "#000000",
      secondary: "#006B5A",
      accent: "#006B5A",
      background: "#FFFFFF",
      surface: "#F0F7F5",
      text: "#1A1A1A",
      muted: "#888888",
    },
    fonts: { display: "system-ui", body: "system-ui", mono: "monospace" },
    borderRadius: "0px",
    shadows: "none",
    borders: "1px solid #D0E8E0",
  },
  {
    id: "wallpaper",
    name: "Wallpaper*",
    category: "editorial",
    colors: {
      primary: "#000000",
      secondary: "#888888",
      accent: "#000000",
      background: "#FFFFFF",
      surface: "#F5F5F5",
      text: "#1A1A1A",
      muted: "#AAAAAA",
    },
    fonts: { display: "system-ui", body: "system-ui", mono: "monospace" },
    borderRadius: "0px",
    shadows: "none",
    borders: "none",
  },
  {
    id: "new-yorker",
    name: "The New Yorker",
    category: "editorial",
    colors: {
      primary: "#000000",
      secondary: "#E23D28",
      accent: "#E23D28",
      background: "#FFFFFF",
      surface: "#FAFAF5",
      text: "#1A1A1A",
      muted: "#888888",
    },
    fonts: { display: "Georgia", body: "Georgia", mono: "monospace" },
    borderRadius: "0px",
    shadows: "none",
    borders: "none",
  },
  {
    id: "vogue",
    name: "Vogue",
    category: "editorial",
    colors: {
      primary: "#000000",
      secondary: "#C4A882",
      accent: "#000000",
      background: "#FFFFFF",
      surface: "#FAFAF5",
      text: "#000000",
      muted: "#AAAAAA",
    },
    fonts: { display: "Georgia", body: "Georgia", mono: "monospace" },
    borderRadius: "0px",
    shadows: "none",
    borders: "none",
  },
  {
    id: "ft",
    name: "Financial Times",
    category: "editorial",
    colors: {
      primary: "#000000",
      secondary: "#FFF1E5",
      accent: "#000000",
      background: "#FFF1E5",
      surface: "#FFFFFF",
      text: "#1A1A1A",
      muted: "#888888",
    },
    fonts: { display: "Georgia", body: "Georgia", mono: "monospace" },
    borderRadius: "0px",
    shadows: "none",
    borders: "1px solid #E0D0C0",
  },

  // ═══════════════════════════════════════════════════════════════
  // CRIATIVO (6)
  // ═══════════════════════════════════════════════════════════════
  {
    id: "dribbble",
    name: "Dribbble",
    category: "criativo",
    colors: {
      primary: "#EA4C89",
      secondary: "#9B51E0",
      accent: "#EA4C89",
      background: "#FFFFFF",
      surface: "#F8F0F5",
      text: "#1A1A1A",
      muted: "#888888",
    },
    fonts: { display: "system-ui", body: "system-ui", mono: "monospace" },
    borderRadius: "12px",
    shadows: "0 4px 20px rgba(234,76,137,0.15)",
    borders: "none",
  },
  {
    id: "behance",
    name: "Behance",
    category: "criativo",
    colors: {
      primary: "#1769FF",
      secondary: "#000000",
      accent: "#1769FF",
      background: "#FFFFFF",
      surface: "#F0F5FF",
      text: "#1A1A1A",
      muted: "#888888",
    },
    fonts: { display: "system-ui", body: "system-ui", mono: "monospace" },
    borderRadius: "8px",
    shadows: "none",
    borders: "1px solid #D0E0FF",
  },
  {
    id: "awwwards",
    name: "Awwwards",
    category: "criativo",
    colors: {
      primary: "#000000",
      secondary: "#C5A059",
      accent: "#C5A059",
      background: "#FFFFFF",
      surface: "#FAFAF5",
      text: "#1A1A1A",
      muted: "#AAAAAA",
    },
    fonts: { display: "system-ui", body: "system-ui", mono: "monospace" },
    borderRadius: "0px",
    shadows: "none",
    borders: "1px solid #E0D8C0",
  },
  {
    id: "lush",
    name: "Lush",
    category: "criativo",
    colors: {
      primary: "#3D1E6D",
      secondary: "#FF6B35",
      accent: "#00B67A",
      background: "#FFFFFF",
      surface: "#F5F0FA",
      text: "#1A1A1A",
      muted: "#888888",
    },
    fonts: { display: "system-ui", body: "system-ui", mono: "monospace" },
    borderRadius: "12px",
    shadows: "none",
    borders: "none",
  },
  {
    id: "glossier",
    name: "Glossier",
    category: "criativo",
    colors: {
      primary: "#F8C8DC",
      secondary: "#FFFFFF",
      accent: "#F8C8DC",
      background: "#FFFFFF",
      surface: "#FFF5F8",
      text: "#1A1A1A",
      muted: "#BBBBBB",
    },
    fonts: { display: "system-ui", body: "system-ui", mono: "monospace" },
    borderRadius: "20px",
    shadows: "0 2px 12px rgba(248,200,220,0.3)",
    borders: "none",
  },
  {
    id: "aesop-light",
    name: "Aesop Light",
    category: "criativo",
    colors: {
      primary: "#3D3229",
      secondary: "#8B7355",
      accent: "#C4956A",
      background: "#FAFAF5",
      surface: "#FFFFFF",
      text: "#3D3229",
      muted: "#9B8E7E",
    },
    fonts: { display: "Georgia", body: "Georgia", mono: "monospace" },
    borderRadius: "0px",
    shadows: "none",
    borders: "1px solid rgba(0,0,0,0.04)",
  },

  // ═══════════════════════════════════════════════════════════════
  // DARK MODE (6)
  // ═══════════════════════════════════════════════════════════════
  {
    id: "discord",
    name: "Discord",
    category: "dark",
    colors: {
      primary: "#5865F2",
      secondary: "#2C2F33",
      accent: "#57F287",
      background: "#2C2F33",
      surface: "#23272A",
      text: "#FFFFFF",
      muted: "#8E9297",
    },
    fonts: { display: "system-ui", body: "system-ui", mono: "monospace" },
    borderRadius: "8px",
    shadows: "0 4px 16px rgba(88,101,242,0.2)",
    borders: "none",
  },
  {
    id: "twitch",
    name: "Twitch",
    category: "dark",
    colors: {
      primary: "#9146FF",
      secondary: "#18181B",
      accent: "#FF6B6B",
      background: "#18181B",
      surface: "#1F1F23",
      text: "#EFEFF1",
      muted: "#848494",
    },
    fonts: { display: "system-ui", body: "system-ui", mono: "monospace" },
    borderRadius: "6px",
    shadows: "0 4px 16px rgba(145,70,255,0.2)",
    borders: "1px solid rgba(255,255,255,0.05)",
  },
  {
    id: "github-dark",
    name: "GitHub Dark",
    category: "dark",
    colors: {
      primary: "#238636",
      secondary: "#0D1117",
      accent: "#58A6FF",
      background: "#0D1117",
      surface: "#161B22",
      text: "#C9D1D9",
      muted: "#8B949E",
    },
    fonts: { display: "system-ui", body: "system-ui", mono: "monospace" },
    borderRadius: "6px",
    shadows: "none",
    borders: "1px solid #30363D",
  },
  {
    id: "raycast-dark",
    name: "Raycast Dark",
    category: "dark",
    colors: {
      primary: "#FF6363",
      secondary: "#1D1D1D",
      accent: "#FFD60A",
      background: "#0D0D0D",
      surface: "#1A1A1A",
      text: "#FFFFFF",
      muted: "#6E6E6E",
    },
    fonts: { display: "system-ui", body: "system-ui", mono: "monospace" },
    borderRadius: "12px",
    shadows: "0 4px 20px rgba(255,99,99,0.1)",
    borders: "1px solid rgba(255,255,255,0.04)",
  },
  {
    id: "linear-dark",
    name: "Linear Dark",
    category: "dark",
    colors: {
      primary: "#5E6AD2",
      secondary: "#171923",
      accent: "#F2C94C",
      background: "#0A0B0F",
      surface: "#14151A",
      text: "#E8E8E8",
      muted: "#5A5A6E",
    },
    fonts: { display: "system-ui", body: "system-ui", mono: "monospace" },
    borderRadius: "8px",
    shadows: "none",
    borders: "1px solid rgba(255,255,255,0.04)",
  },
  {
    id: "vercel-dark",
    name: "Vercel Dark",
    category: "dark",
    colors: {
      primary: "#FFFFFF",
      secondary: "#A1A1AA",
      accent: "#0070F3",
      background: "#000000",
      surface: "#0A0A0A",
      text: "#FFFFFF",
      muted: "#666666",
    },
    fonts: { display: "system-ui", body: "system-ui", mono: "monospace" },
    borderRadius: "0px",
    shadows: "none",
    borders: "1px solid #222222",
  },

  // ═══════════════════════════════════════════════════════════════
  // COLORIDO (4)
  // ═══════════════════════════════════════════════════════════════
  {
    id: "figma-colorful",
    name: "Figma Colorful",
    category: "colorido",
    colors: {
      primary: "#F24E1E",
      secondary: "#A259FF",
      accent: "#0ACF83",
      background: "#FFFFFF",
      surface: "#F5F5F5",
      text: "#1E1E1E",
      muted: "#888888",
    },
    fonts: { display: "system-ui", body: "system-ui", mono: "monospace" },
    borderRadius: "12px",
    shadows: "0 4px 20px rgba(0,0,0,0.1)",
    borders: "none",
  },
  {
    id: "notion-colorful",
    name: "Notion Colorful",
    category: "colorido",
    colors: {
      primary: "#2EAADC",
      secondary: "#FF7369",
      accent: "#FBBF24",
      background: "#FFFFFF",
      surface: "#F7F6F3",
      text: "#37352F",
      muted: "#9B9A97",
    },
    fonts: { display: "system-ui", body: "system-ui", mono: "monospace" },
    borderRadius: "8px",
    shadows: "none",
    borders: "1px solid #E0DDD8",
  },
  {
    id: "stripe-rainbow",
    name: "Stripe Rainbow",
    category: "colorido",
    colors: {
      primary: "#635BFF",
      secondary: "#00D4AA",
      accent: "#FF7A00",
      background: "#0A2540",
      surface: "#1A3550",
      text: "#FFFFFF",
      muted: "#8898AA",
    },
    fonts: { display: "system-ui", body: "system-ui", mono: "monospace" },
    borderRadius: "12px",
    shadows: "0 4px 24px rgba(99,91,255,0.25)",
    borders: "1px solid rgba(255,255,255,0.08)",
  },
  {
    id: "vercel-gradient",
    name: "Vercel Gradient",
    category: "colorido",
    colors: {
      primary: "#0070F3",
      secondary: "#7928CA",
      accent: "#FF0080",
      background: "#000000",
      surface: "#111111",
      text: "#FFFFFF",
      muted: "#888888",
    },
    fonts: { display: "system-ui", body: "system-ui", mono: "monospace" },
    borderRadius: "12px",
    shadows: "0 8px 32px rgba(0,112,243,0.2)",
    borders: "1px solid rgba(255,255,255,0.06)",
  },

  // ═══════════════════════════════════════════════════════════════
  // PREMIUM (4)
  // ═══════════════════════════════════════════════════════════════
  {
    id: "rolex",
    name: "Rolex",
    category: "premium",
    colors: {
      primary: "#006039",
      secondary: "#A37E2C",
      accent: "#A37E2C",
      background: "#000000",
      surface: "#0A0A0A",
      text: "#FFFFFF",
      muted: "#888888",
    },
    fonts: { display: "Georgia", body: "Georgia", mono: "monospace" },
    borderRadius: "0px",
    shadows: "0 4px 20px rgba(163,126,44,0.15)",
    borders: "1px solid rgba(163,126,44,0.2)",
  },
  {
    id: "cartier",
    name: "Cartier",
    category: "premium",
    colors: {
      primary: "#C41E3A",
      secondary: "#000000",
      accent: "#C41E3A",
      background: "#FFFFFF",
      surface: "#FAFAFA",
      text: "#000000",
      muted: "#888888",
    },
    fonts: { display: "Georgia", body: "Georgia", mono: "monospace" },
    borderRadius: "0px",
    shadows: "none",
    borders: "none",
  },
  {
    id: "louis-vuitton",
    name: "Louis Vuitton",
    category: "premium",
    colors: {
      primary: "#5C3317",
      secondary: "#D4A574",
      accent: "#D4A574",
      background: "#1A1A1A",
      surface: "#2A2A2A",
      text: "#FFFFFF",
      muted: "#888888",
    },
    fonts: { display: "Georgia", body: "Georgia", mono: "monospace" },
    borderRadius: "0px",
    shadows: "0 4px 20px rgba(212,165,116,0.15)",
    borders: "1px solid rgba(212,165,116,0.2)",
  },
  {
    id: "tiffany",
    name: "Tiffany",
    category: "premium",
    colors: {
      primary: "#0ABAB5",
      secondary: "#000000",
      accent: "#0ABAB5",
      background: "#FFFFFF",
      surface: "#F0FAFA",
      text: "#1A1A1A",
      muted: "#888888",
    },
    fonts: { display: "Georgia", body: "Georgia", mono: "monospace" },
    borderRadius: "0px",
    shadows: "none",
    borders: "1px solid #D0EDED",
  },
];
